version: '3.8'

services:
  web:
    build: ./project
    command: 
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.sh 
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:16-bullseye
    volumes:
      - new_homesite_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - 5431:5432
volumes:
  new_homesite_data_dev:
