version: '3.8'

services:
  web:
    build:
      context: ./project
      dockerfile: Dockerfile.prod
    command: 
      - /bin/sh
      - -c
      - |
        . /usr/src/app/entrypoint.prod.sh
        python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - rabbitmq
      - db

    
  webpack:
    build: ./node_staticfiles
    command: npm run webpack
    volumes:
      - ./node_staticfiles:/node
      - ./project:/project
    env_file:
      - ./node_staticfiles/.env.prod
    depends_on:
      - web
  
  db:
    image: postgres:16-bullseye
    volumes:
      - postgres_data_stage:/var/lib/postgresql/data/
    env_file:
      - ./.env.database
    ports:
      - 5431:5432

volumes:
  postgres_data_stage: